# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

    name = "hackthedinos"
    offset = 0

    # shared folder mapping and permissions
    config.vm.synced_folder "..", "/var/www/hackthedinos", group: "www-data", :mount_options => ['dmode=775','fmode=775']
    config.vm.synced_folder "..", "/home/vagrant/project", group: "www-data", :mount_options => ['dmode=777','fmode=777']

    config.vm.network :forwarded_port, guest: 80, host: 8080 + offset, auto_correct: true
    config.vm.network :forwarded_port, guest: 3306, host: 3306 + offset, auto_correct: true

    ####################################################
    # No further configuration needed below this point
    ####################################################

    config.vm.hostname = name + "-dev"

    config.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--rtcuseutc", "on"]
        vbox.customize ["modifyvm", :id, "--name", name + "_vagrant"]
    end

    config.vm.synced_folder "salt/root/", "/srv/salt/"
    config.vm.synced_folder "salt/pillar/", "/srv/pillar/"
    config.vm.synced_folder "salt/etc/", "/etc/salt/"

    config.vm.provision :salt do |salt|
        salt.bootstrap_options = "-P"
        salt.minion_config = "salt/minion"
        salt.run_highstate = true
        salt.verbose = true
    end

    config.vm.define name + "_dev" do |vmc|
        vmc.vm.box = "ubuntu/trusty64"
        vmc.vm.box_check_update = true
    end

end
